apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-flask-app
spec:
  replicas: 8
  template:
    metadata:
      labels:
        app: k8s-flask-app
    spec:
      containers:
        - name: k8s-flask-app
          image: biancarosa/k8s-flask-app
          envFrom:
            - configMapRef:
                name: k8s-flask-app-env
            - secretRef:
                name: k8s-flask-app-secrets
